### PR TITLE
More button no longer switches view until period is selected

### LINKED ISSUE #272: Tapping "More" then cancel does not restore previous tab.
To reproduce:

- On an iPhone pull up the stats screen. 
- Be in portrait orientation
- Have the Insights tab selected.
- Tap the More button. 
- Cancel the action sheet that appears. 
- You are now on the Days tab instead of the Insights tab. 

It looks like just tapping the more button is causing the switch to the Days stats

### PR DESCRIPTION
**Pull request by astralbodies**
Fixes #272 
Depends on #274 being merged first

When tapping more, the view is no longer changed to the first stats period segment.

Needs Review: @aerych

### CODE REVIEW

**Comment by astralbodies** [comment]
cc: @daniloercoli

**Comment by aerych** [comment]
Hi Aaron.  I noticed that if I have Insights selected, and I tap more, then select a date, the selection in the segment control moves to the date, but the controller still shows Insights.  If the date segment is the one selected, and I tap more and select a different date, then it updates as expected.

**Comment by astralbodies** [comment]
Ooh good catch, @aerych!

**Comment by aerych** [comment]
Works great after the change. :shipit:

**Comment by astralbodies** [comment]
I really appreciate the time you took to help test this @aerych!

**Pull request merged**
