### PR TITLE
Fix UI for untitled Posts

### PR DESCRIPTION
**Pull request by elibud**
Following what Calypso does, for untitled posts we'll display: **(no title)**

notitle

**Fixes:** 
https://github.com/wordpress-mobile/WordPress-iOS/issues/5212

**To test:** 
Create an untitled post in one of your blogs and run the demo app for that blog.
simulator screen shot mar 17 2017 11 36 59

### CODE REVIEW

**Comment by astralbodies** [comment]
I'm seeing conflicting logic on how untitled posts are displayed in the main app - between `(Untitled)` and `(no title)`. I'm checking with the Calypso devs to see how the posts are shown in stats so we match. I *think* we show post URLs for posts without titles in the stats screens.

**Comment by elibud** [comment]
Yes I did notice that they use both #postId (untitled) and (no title). I went with the first option to be able to differentiate across several untitled posts.

**Comment by elibud** [comment]
I think I may have misunderstood you, you wanna follow Calypso exactly and display (no title) on Insights but display #postId (untitled) on the post lists?

**Comment by astralbodies** [comment]
> I think I may have misunderstood you, you wanna follow Calypso exactly and display (no title) on Insights but display #postId (untitled) on the post lists?

Yup that's correct! #postId (untitled) actually comes from the API side so you shouldn't have to make any change there. For the Insights post performance section lets match Calypso for now.

**Comment by elibud** [comment]
@astralbodies done!

**Pull request merged**
