### PR TITLE
Cocoapods framework support, take 2

### PR DESCRIPTION
**Pull request by koke**
I rebased #344 and cherry-picked the commits to revert the revert. Also added fixes to the demo project and fixed some problems with bundles.

What I've tested:

- StatsDemo builds, runs, and seems to work fine
- All tests green
- WordPress-iOS builds, runs, stats views load and have all the images. You might want to double check that. I'll update #4435 to point to this branch in a bit, or you can edit the Podfile

Refs https://github.com/wordpress-mobile/WordPress-iOS/issues/4434

Needs Review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
Okay I'm doing the review now, @koke.  I cannot wait!!!!

**Comment by astralbodies** [comment]
@koke :shipit: 

I updated the header_dir for the project to get rid of the underscores. I'm not entirely happy with `WordPressComStatsiOS` but it works.

**Comment by koke** [comment]
Maybe rename it to `WordPressComStats` for a next version?

**Comment by astralbodies** [comment]
Yeah I'm more okay with that ;)

**Pull request merged**
