### PR TITLE
Updates to iOS 9 and removes deprecated methods

### LINKED ISSUE #328: Move to only support iOS 9

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #328 

Updates to iOS 9 as the base target for the main project and StatsDemo. Removed all deprecation warnings which was somewhat limited to old rotation techniques and action sheet usage.

**Things to test:**
* Rotations
* Smaller screens and the `More...` action sheet usage. Rotations should cancel it.
* Maybe multitasking

**Note:** I did see some weird font issues in the graph when switching to weeks (I think). The labels under the bar weren't resizing properly. I believe that issue isn't directly tied to any of the changes made here but rather something coming up without using autolayout in those collection view cells. Will open an issue for this.

Needs Review: @jleandroperez
cc: @sendhil

### CODE REVIEW

**Comment by jleandroperez** [comment]
#### Constraints Error:
1. Launch StatsDemo on the 6s
2. Tap over Days
3. Scroll all the way down
4. Rotate (Landscape)
5. Tap over More
6. Cancel and dismiss the alertView
7. Rotate again (Portrait)

As a result, i'm getting the error pasted below:

```
2015-10-21 15:05:43.759 StatsDemo[272:11239] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1258712e0 UITableViewCellContentView:0x12586ee50.trailingMargin == UILabel:0x1258749c0'View All'.trailing + 15>",
    "<NSLayoutConstraint:0x125871330 H:|-(23)-[UILabel:0x1258749c0'View All']   (Names: '|':UITableViewCellContentView:0x12586ee50 )>",
    "<NSLayoutConstraint:0x125878d20 'UIView-Encapsulated-Layout-Width' H:[UITableViewCellContentView:0x12586ee50(45)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1258712e0 UITableViewCellContentView:0x12586ee50.trailingMargin == UILabel:0x1258749c0'View All'.trailing + 15>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-10-21 15:05:43.761 StatsDemo[272:11239] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x124755c60 H:[UIImageView:0x1245d4ba0(20)]>",
    "<NSLayoutConstraint:0x12475b1e0 H:|-(23)-[UIImageView:0x1245d4ba0]   (Names: '|':UITableViewCellContentView:0x124744580 )>",
    "<NSLayoutConstraint:0x124751270 H:[UIImageView:0x1245d4ba0]-(8)-[UILabel:0x1247c5b20'Czech Republic']>",
    "<NSLayoutConstraint:0x12458f720 H:[UILabel:0x1245bbde0'1']-(23)-|   (Names: '|':UITableViewCellContentView:0x124744580 )>",
    "<NSLayoutConstraint:0x124754c20 H:[UILabel:0x1247c5b20'Czech Republic']-(10)-[UILabel:0x1245bbde0'1']>",
    "<NSLayoutConstraint:0x1245945c0 'UIView-Encapsulated-Layout-Width' H:[UITableViewCellContentView:0x124744580(83)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x124755c60 H:[UIImageView:0x1245d4ba0(20)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

**Comment by jleandroperez** [comment]
#### Xcode 7.0.1 warnings:

I'm getting the following warnings, while building using Xcode 7.01:

```
/Users/Lantean/Engineering/Automattic/WordPressCom-Stats-iOS/StatsDemo/StatsDemo/WPSAppDelegate.m:41:40: 'setStatusBarStyle:animated:' is deprecated: first deprecated in iOS 9.0 - Use -[UIViewController preferredStatusBarStyle]
/Users/Lantean/Engineering/Automattic/WordPressCom-Stats-iOS/StatsDemo/StatsDemo/WPSAppDelegate.m:44:23: 'appearanceWhenContainedIn:' is deprecated: first deprecated in iOS 9.0 - Use +appearanceWhenContainedInInstancesOfClasses: instead
/Users/Lantean/Engineering/Automattic/WordPressCom-Stats-iOS/StatsDemo/StatsDemo/WPSAppDelegate.m:45:23: 'appearanceWhenContainedIn:' is deprecated: first deprecated in iOS 9.0 - Use +appearanceWhenContainedInInstancesOfClasses: instead
/Users/Lantean/Engineering/Automattic/WordPressCom-Stats-iOS/StatsDemo/StatsDemo/WPSAppDelegate.m:46:17: 'appearanceWhenContainedIn:' is deprecated: first deprecated in iOS 9.0 - Use +appearanceWhenContainedInInstancesOfClasses: instead
```

**Comment by astralbodies** [comment]
Fixed the warnings in StatsDemo, @jleandroperez. Can you try getting the warning again with Xcode 7.1 and iOS 9.1? I can't reproduce.

**Comment by astralbodies** [comment]
@jleandroperez Ready for another review ;)

**Comment by jleandroperez** [comment]
Looking great @astralbodies, constraint errors gone!

:shipit:

**Comment by astralbodies** [comment]
Thanks @jleandroperez!!

**Comment by jleandroperez** [comment]
Anytime!

**Pull request merged**
