### PR TITLE
Adding the ability to get stats service from the delegate

### PR DESCRIPTION
**Pull request by nheagy**
A prerequisite for wordpress-mobile/WordPress-iOS#5590

Needs review: @bummytime

### CODE REVIEW

**Comment by astralbodies** [comment]
This *might* present issues if the intention is to share the StatsService instance between view controllers. @SergioEstevao what do you think?

**Comment by SergioEstevao** [comment]
@astralbodies I think it's ok, we can have multiple batches going in parallel.
The NSURLSession will be shared between all the VC, but it will be ok, Apple actually recommends to have one NSURLSession and use it for multiple connections instead of creating one for each request.
And because all this goes to WP.com I think the performance will be great.

**Comment by bummytime** [comment]
Totally agree with @SergioEstevao. :shipit: @nheagy!

**Comment by nheagy** [comment]
Thanks for the review(s) @bummytime @astralbodies @SergioEstevao

**Pull request merged**
