### PR TITLE
Design Review Corrections / Updates

### LINKED ISSUE #240: Styling Changes
From: @jancavan

- [x] Add more padding between y-axis and edge of module
- [x] Active x-axis should not be highlighted or have a background color
- [x] Inactive x-axis color should be darken( $gray, 30% ), not $blue-medium
- [x] Remove top border on active tabs
- [x] Expanded lists have 2 top borders, one lighter and the other darker. Please remove the lighter one (topmost)
- [x] Chevron color should be updated to $gray
- [x] Parent lists should have the globe icon
- [x] We can just use a link icon for those URLs that open in a browser window since the right arrow indicates that there are more options in the next screen.
- [x] ~~Can we have these options in the in-app browser – back/forward arrows, page title (with URL at the bottom), refresh and dismiss (x)? Currently, they can only go back, but there’s no way to move forward.~~ => moved to https://github.com/wordpress-mobile/WordPress-iOS/issues/3602
- [x] Some link colors are blue but some are black. All link colors should be $blue-wordpress
- [x] Remove border below segmented control. I think in the past I said this looks ok, sorry about that! On the corrected image, I also added a bit more padding between the module heading and segmented control.
- [x] This kind of preloader feels less obtrusive and users can still switch between tabs.

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #240 

Implements the styling changes that @jancavan listed out. See original issue for the list and items moved to separate issues.

cc: @daniloercoli

### CODE REVIEW

**Comment by astralbodies** [comment]
@bummytime You maybe want to take a stab at the code review for this PR?

**Comment by bummytime** [comment]
@astralbodies sure thang.

**Comment by daniloercoli** [comment]
While testing this PR I found an issue with the followers module. Tracked here: https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/issues/251

**Comment by astralbodies** [comment]
:shipit: per @jancanvan

**Pull request merged**
