### PR TITLE
Resolves Xcode 7.3 Storyboard warnings

### PR DESCRIPTION
**Pull request by astralbodies**
h/t to @kurzee and @frosty for the assistance on resolving these errors/warnings.

Testing: 
1. Open the Storyboard in Xcode 7.3.
2. Bask in its warningless glory.
3. Profit.

Needs Review: @kurzee

### CODE REVIEW

**Comment by kurzee** [comment]
The `UIStackView` for the "Best Views Ever" label still has the distribution set to fill.

**Comment by kurzee** [comment]
Some stackViews are using the fill alignment and others the center. I think it might be best to set them all as either center or fill.

**Comment by astralbodies** [comment]
@kurzee Oops I didn't mean to do that. Set all of those stack views to alignment center, fill proportionately.

**Comment by kurzee** [comment]
@astralbodies looks good :shipit: :dancer: :shipit: :dancer:

**Comment by astralbodies** [comment]
Thanks for the review and help!

**Pull request merged**
