### PR TITLE
Update to CocoaPods 1.0

### LINKED ISSUE #407: Migrate to CocoaPods 1.0

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #407 

Updated configuration to the latest for CocoaPods 1.0. 

Testing:
1. Build and Test the main project.
2. Build and run the StatsDemo project.

Needs Review: @kwonye

### CODE REVIEW

**Comment by kwonye** [comment]
@astralbodies I'm unable to run tests

**Comment by astralbodies** [comment]
Yeah I see that with Travis too 👎 

Will try to resolve tonight.

**Comment by astralbodies** [comment]
@kwonye Can you do a `pod update` and see what happens? I did an update on my other computer after I couldn't install pods. The weird thing is the lock file didn't change...

**Comment by astralbodies** [comment]
@kwonye NOW give it a try. I swear I did the deintegrate and install trick already.

**Comment by kwonye** [comment]
Other than worrying about your sanity after reading the commit messages, everything looks good!

:shipit:

**Comment by astralbodies** [comment]
@kwonye Thanks for the review! I suspect my commit messages are just going to get worse.

**Pull request merged**
