### PR TITLE
Update WordPress-Shared-iOS dependency to 0.6.0

### PR DESCRIPTION
**Pull request by kurzee**
Updates WordPress-Shared-iOS dependency to version 0.6.0.

Needs review: @astralbodies

### CODE REVIEW

**Comment by astralbodies** [comment]
@kurzee Don't forget to actually update the podspec 😁

**Comment by kurzee** [comment]
@astralbodies ah good catch! Updated.

**Comment by astralbodies** [comment]
@kurzee You may also want to, for good measure, do a `pod update` in the `StatsDemo` subfolder.

**Comment by kurzee** [comment]
@astralbodies ah didn't know that either, a few updated as seen in https://github.com/wordpress-mobile/WordPressCom-Stats-iOS/pull/422/commits/7bac04e41f8b986112b43391fd6145d9e2050659

**Comment by astralbodies** [comment]
:shipit: after the Travis build is done 😄

**Comment by kurzee** [comment]
@astralbodies awesome, thanks!

**Pull request merged**
