### PR TITLE
Splits stats pod into two subspecs

### LINKED ISSUE #338: Split the pod into subspecs
Split the entire repo into at least two subspecs - UI and non-UI (services, effectively). This helps resolves problems with code that isn't appropriate for app extensions in WPiOS.

cc: @koke

### PR DESCRIPTION
**Pull request by astralbodies**
Closes #338 

Splits the stats pod into two subspecs - UI and Services. This will help facilitate movement towards frameworks and improvement in code for use when not in a UI environment (or when operation aren't available like in WatchKit.)

Needs Review: @sendhil, @koke, @bummytime

### CODE REVIEW

**Comment by sendhil** [comment]
Aside from one comment looks good to me @astralbodies

**Comment by astralbodies** [comment]
Thanks for reviewing @sendhil - I fixed the spacing issue.

@koke for now you can point the pod at the develop branch and specify only `WordPressCom-Stats-iOS/Services` in the Today Widget Podfile.

**Comment by koke** [comment]
`StatsGroup.h` imports `StatsSection.h` which is in the UI subspec, so the Today Widget fails to build

screen shot 2015-11-09 at 12 40 41

**Comment by astralbodies** [comment]
D'OH! Thanks for catching! Reopening.

**Pull request merged**
